### ISSUE TITLE
datasets or graphs in yaml config ?

### ISSUE THREAD

**Issue by momo54** [sage-org/sage-engine#11]
Dear all,

The sage server expects graph definitions within  "graphs:" inside config.yaml
and 'sage-postgres-init' expects graph definitions within "datasets:"

So "graphs:" or "datasets:" :)

**Comment by Callidon** [comment]
Fixed in c033e18286ed888728b899c3048dd4bc61605e67, the engine uses `graphs` instead of `datasets`, to keep up with the W3C specifications.
